import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { MobileDrawerNav } from '@/src/components/layout/MobileDrawerNav';
import { DesktopSidebar } from '@/src/components/layout/DesktopSidebar';
import { QueryProvider } from '@/src/components/QueryProvider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col lg:flex-row">
        <QueryProvider>
          <MobileDrawerNav />
          <DesktopSidebar />
          <main className="flex-1 min-w-0 bg-zinc-50">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
