import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { SidebarNav } from '@/src/components/layout/SidebarNav';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex">
        <aside className="w-64 shrink-0 border-r border-zinc-200 bg-zinc-800">
          <Link href={'/'}>
            <div className="px-6 py-6">
              <div className="text-lg font-bold text-zinc-200">MENTOFOLIO</div>
              <div className="text-xs text-zinc-400 mt-1">voice studio</div>
            </div>
          </Link>
          <SidebarNav />
        </aside>
        <main className="flex-1 min-w-0 bg-zinc-50">{children}</main>
      </body>
    </html>
  );
}
